### ISSUE TITLE
tests: test all the commands [5h]

### ISSUE THREAD

**Issue by annatrz** [cernanalysispreservation/cap-client#101]
Install `cap-client` locally with current master and try **all** the commands. 
Prepare a note with every command you run and the output you've got.

Example:
`cap-client --help` to see all the commands
```
Usage: cap-client [OPTIONS] COMMAND [ARGS]...

  CAP Client for interacting with CAP Server.

Options:
  -v, --verbose                   Verbose output
  -l, --loglevel [error|debug|info]
                                  Sets log level
  -t, --access_token TEXT         Sets users access token
  --help                          Show this message and exit.

Commands:
  clone         Clone analysis with given pid.
  create        Create an analysis.
  delete        Delete analysis with given pid.
  files         Files managing commands.
  get           Retrieve one or all analyses from a user.
  get-schema    Retrieve analysis schema.
  get-shared    Retrieve one or all shared analyses from a user.
  me            Retrieve user info.
  metadata      Metadata managing commands.
  permissions   Permissions managing commands.
  publish       Publish analysis with given pid.
  repositories  Repositories managing commands.
  types         Retrieve all types of analyses.
```
`cap-client metadata --help` pick one to test, use help to see all the commands in metadata group
```
Usage: cap-client metadata [OPTIONS] COMMAND [ARGS]...

  Metadata managing commands.

Options:
  --help  Show this message and exit.

Commands:
  append  Edit analysis field adding a new value to an array.
  get     Retrieve one or more fields in analysis metadata.
  remove  Remove analysis field.
  set     Edit analysis field value.
```
`cap-client metadata get --help` see what can be parameters for metadata `get` method
```
Usage: cap-client metadata get [OPTIONS] [FIELD]

  Retrieve one or more fields in analysis metadata.

Options:
  -p, --pid TEXT  Get metadata of the deposit with given pid  [required]
  --help          Show this message and exit.
```
So you see it needs a `pid` argument, which is required, so it means, you have to test three cases: 
* when existing PID passed `cap-client metadata get --pid non-existing-pid` 
* when non-existing pid passed `cap-client metadata get --pid existing-pid`
* when no pid passed `cap-client metadata get`

Write down all the commands you run and output/error you've got.

**Comment by Lilykos** [comment]
[Here](https://github.com/cernanalysispreservation/cap-client/wiki/CLI-commands:-tests-and-results) are the results, most of the commands work just fine, although there are a couple of issues:

- error messages are mostly generic, could use some work
- permissions/clone deposit are not interacting correctly with CAP
- we should think about unifying some elements of the way the client works

**Comment by annatrz** [comment]
So to sum up:

* we need context in which you were testing - just create few analyses before you start, some from a different user, who gave you some access, some from another member of collaboration that is published, some that is published and you have no access to, in general, have analyses that you have different kind of access to - describe it on the top, so we know what we are looking at:)

* for commands that caused errors, use --verbose flag, write down what was an output, if got 500 you can also attach server logs - this would be very helpful!

* and here some test cases that you missed:
- [ ] Verbose flag
- [ ] Log-level info flag
- [ ] Log-level error flag
- [ ] Log-level debug flag
- [ ] Access token passed as parameter for command
- [ ] Publish when already published record
- [ ] Publish when no permission
- [ ] Delete when no permission
- [ ] Get with pid when no permission
- [ ] Get returns only user ones
- [ ] Get -all returns all that user has access to (create from another user and give access)
- [ ] Get-shared with pid when no permission
- [ ] Get-shared returns only user ones
- [ ] Get-shared -all returns all from user collaboration (create from another user and share)
- [ ] Metadata set with nested field
- [ ] Metadata set with array field
- [ ] Metadata get with nested field
- [ ] Metadata get with array field
- [ ] Metadata remove with nested field
- [ ] Metadata remove with array field
- [ ] Download file with —output-file flag
- [ ] Download file when file doesn’t exist
- [ ] Upload file with —output-file flag
- [ ] Upload file with —docker flag
- [ ] Repositories upload with release web hook
- [ ] Repositories upload with push web hook
- [ ] Repositories upload without creating web hook
- [ ] Repositories upload when no permission
- [ ] Clone when no permission
- [ ] Clone
- [ ] Permissions add when user have no admin permission
- [ ] Permissions remove

**Comment by annatrz** [comment]
Perfect, thank you, this is really helpful!
Let's leave this issue open till we create separate issues for all the fixes

**Comment by annatrz** [comment]
Solved:)
