### ISSUE TITLE
Remove additional properties on create 

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [cernanalysispreservation/cap-client#12]
If the user provides information that are not in our schema we should remove them before creating the deposit

**Comment by tiborsimko** [comment]
It would be better to return the validation error back to the client rather than silently removing input properties.  If there is a need to override such a "true" validation, we could have a CLI option for that, for example `cap upload --remove-invalid my.json`.

**Comment by ioannistsanaktsidis** [comment]
>> It would be better to return the validation error back

@tiborsimko yes exactly thats the idea, we just need to figure out how we are going to develop this because we use ```allOf``` in our schemas and it doesn't work properly with the ```additionalProperties``` .

**Comment by ioannistsanaktsidis** [comment]
Closing as already handled on the server side.
