### ISSUE TITLE
files: ask user when overwriting local file on `files download`

### ISSUE THREAD

**Issue by annatrz** [cernanalysispreservation/cap-client#145]
currently when file already exists we just overwrite it silently, we should ask user for confirmation

**Comment by ParthS007** [comment]
@pamfilos What is the expected result here?

I am assuming that, I have to show a prompt if there exist a `file` with the same [`filename` or `output_filepath`](https://github.com/cernanalysispreservation/cap-client/blob/master/cap_client/api/files_api.py#L73).

I will follow these steps:

- First, Check if there exist a `file` with the same `filename` or `output_filepath`
- If there exist a file, Client will prompt for confirmation(yes/no question) with help of [click.confirm](https://click.palletsprojects.com/en/8.0.x/api/#click.confirm)
- No: Abort the download
- Yes: Overwrite the file

Please let me know wdyt?

**Comment by pamfilos** [comment]
Above is perfect. Lets also add an `overwrite/yes-i-know` argument for scripts

**Comment by ParthS007** [comment]
okay, What I understand here is add an `overwrite` argument for [`download` files command](https://github.com/cernanalysispreservation/cap-client/blob/master/cap_client/cli/files_cli.py#L103)in the CLI?

**Comment by pamfilos** [comment]
Yes. So wee need:
- [ ] First, Check if there exist a file with the same filename or output_filepath
- [ ] If `--yes-i-know` flag option, just overwrite without prompt
- [ ] If there exist a file, Client will prompt for confirmation(yes/no question) with help of click.confirm
    - [ ] No: Abort the download
    - [ ] Yes: Overwrite the file
