### ISSUE TITLE
Add option to get only analysis created by user

### ISSUE THREAD

**Issue by annatrz** [cernanalysispreservation/cap-client#20]
Now _get_ returns all analysis that user has access to. 
Add option to retrieve only those created by user.

**Comment by tiborsimko** [comment]
I guess "get mine" should be the default behaviour of the client, while "get all-i-can-see" could be a CLI option.

**Comment by ioannistsanaktsidis** [comment]
Just need to add a ```q``` parameter to the request and it will be ok  e,g
. https://ioanniss-mbp.dyndns.cern.ch:5000/api/deposits/?q=_deposit.created_by:6
