### ISSUE TITLE
cli: refactor structure of cap-client commands

### ISSUE THREAD

**Issue by pamfilos** [cernanalysispreservation/cap-client#44]
**cap-client** resources:
  - [x] me
  - [x] metadata [PID]
      - [x] get [PATH]
      - [x] set [PATH] —file <file_to_upload> —ref <url_ref_record_ti_point>
      - [x] append [PATH] <JSON>
      - [x] remove [PATH] <JSON>
  - [x] files [PID]
      - [x] get [file_key_as_on_cap_server] [output_file]
      - [x] upload [FILE] [file_metadata]
      - [x] remove [PATH] <JSON>      
  - [x] permissions [PID]
      - [x] get [SCOPE (“read”, “update”, “admin”)]
      - [x] add [SCOPE (“read”, “update”, “admin”)]  --user [EMAIL]
      - [x] remove [SCOPE (“read”, “update”, “admin”)]  --user [EMAIL]
  - [x] get [PID]
  - [x] create [DEPOSIT_TYPE] —json <json_metadata_file>
  - [x] delete [PID]
  - [x] publish [PID]
  - [x] clone [PID]
  - [x] get-shared [PID]
  - [x] types
    

-------------

Anything else we might need, changes?

**Comment by annatrz** [comment]
with structure like this we're getting really long commants, like: 
```cap-client deposit metadata set field_name field_value --file file_path```
maybe deposit operations should be the default ones, and as we have only two commands record related, we will have sth like get-shared and clone-shared?
