### ISSUE TITLE
cli: dir upload to delete leftover tar file

### ISSUE THREAD

**Issue by atrisovic** [cernanalysispreservation/cap-client#86]
<img width="283" alt="screen shot 2018-07-24 at 12 00 35" src="https://user-images.githubusercontent.com/13986265/43131468-65da4d7e-8f39-11e8-823e-1fe64ca8ce5b.png">

the tar file stays in the system (see fig.), while it should be deleted after the upload

Description:

while uploading a directory for example: `cap-client -v files upload newdir -p bf6b8501822c4d2ba46028611354df7e`

the client creates a temporary tar file which remains in the system after the upload is over.

**Comment by annatrz** [comment]
already fixed in #141
